### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by tlepoint** [quarkslab/NFLlib#12]
Hi,

What do you think of doing releases of NFLlib (so that it could be handle by package managers)?

**Comment by carlosaguilarmelchor** [comment]
Indeed, we should do a release. Maybe after we merge the PR for serialization ? 

When you talk of package managers you are thinking of a specific automated process ?

**Comment by tlepoint** [comment]
I was thinking of classical packages managers (apt-get, pacman, brew, macports, etc.).

**Comment by aguinet** [comment]
That can be a good idea indeed :)
What can be done on github is to tag a specific commit in the master branch, and tell github that this is a release : https://help.github.com/articles/creating-releases/

**Comment by carlosaguilarmelchor** [comment]
@tlepoint I completely agree that would be great. What I was asking was if we could automate the process so that each time we make a release packages for classic package managers could be added automatically.  

In any case I agree for releases and for packages.

**Comment by carlosaguilarmelchor** [comment]
One question @tlepoint you were thinking about source packages (that will once installed allow the user to compile NFLlib) or binary packages ?

**Comment by tlepoint** [comment]
I meant was Adrien said, tag a version as a release. I am not particularly in favor of proposing binary packages on a website. Whether it will be included in some package managers, either compiled or not, is something I find orthogonal.

**Comment by carlosaguilarmelchor** [comment]
Well I am ok then for releases.

**Comment by tlepoint** [comment]
Version 1.0.0 after the PR is merged?

**Comment by carlosaguilarmelchor** [comment]
Yes go ahead !
