### ISSUE TITLE
Don't compile tests with make

### ISSUE THREAD

**Issue by tlepoint** [quarkslab/NFLlib#13]
Is it possible to modify the cmake files to avoid the compilation of the tests when only "make" is used?

**Comment by carlosaguilarmelchor** [comment]
+1

**Comment by serge-sans-paille** [comment]
On Tue, May 10, 2016 at 01:09:34AM -0700, Carlos Aguilar Melchor wrote:
> +1

I'll have a look at it

**Comment by serge-sans-paille** [comment]
See #15

**Comment by tlepoint** [comment]
Thanks!
