### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by gbonnoron** [quarkslab/NFLlib#20]
Hi everyone,

I ran into some problems with the "make test" (I follow the build instructions on the github). Many tests (53 or 101 out of 122) fail to compile because of missing refs to chrono related functions. Adding a "#include <chrono>" to tests/tools.h fix this.

Then I run inot other issues. Tests 98, 114 and 118 segfault.
Let me know what information you need to tackle that !

Guillaume

**Comment by serge-sans-paille** [comment]
Hi @gbonnoron . What a small world :-)

I'm able to reproduce this, I'll yell at the culprit, fix this and get back to you :-)

**Comment by serge-sans-paille** [comment]
#21 fixes the trivial issue, I still experiment a few segfaults.

**Comment by serge-sans-paille** [comment]
@gbonnoron if you run `ulimit -s unlimited` before running the test, do you still have the issues? (I don't)

**Comment by gbonnoron** [comment]
Hello @serge-sans-paille !
Thanks for your quick reply :-) It works also for me with unlimited stack size.

**Comment by carlosaguilarmelchor** [comment]
Hi @serge-sans-paille was I the culprit ? ;)

**Comment by carlosaguilarmelchor** [comment]
More seriously, should we move tests from poly_t to poly_p to avoid stack size issues ?

**Comment by tlepoint** [comment]
I thought we had done it, but apparently no. The question is how do we deal with `tests/poly_p.cpp` for large parameters? Maybe we could allow that test to fail (is it possible @serge-sans-paille?).

**Comment by serge-sans-paille** [comment]
one way to handle this would be to statically switch from one implem to the other depending on the (staticaly known) size. I'll have a look at it.

**Comment by carlosaguilarmelchor** [comment]
Maybe we could tell cmake to do ulimit -s before the test ?

**Comment by serge-sans-paille** [comment]
On Tue, Dec 06, 2016 at 01:50:26AM -0800, Carlos Aguilar Melchor wrote:
> Maybe we could tell cmake to do ulimit -s before the test ? 

That would be a terrible hack :-/
And that's too platform dependent...

**Comment by carlosaguilarmelchor** [comment]
Solved by PR#47
