### ISSUE TITLE
Linkage issue for multiple-source files

### ISSUE THREAD

**Issue by gendx** [quarkslab/NFLlib#24]
I created a project with several .cpp source files that #include <nfl.hpp>. When I link my code with the library I get the following linker error:

```
multiple definitions of « nfl::newton_raphson(double, double, int) »
```

Indeed, the function is implemented in the header file `NFLlib/include/nfl/prng/FastGaussianNoise.hpp` (line 136), so is defined in every of my .cpp files that includes it. A quick fix would be to mark it `inline`; alternatively to move its implementation to a .cpp file compiled in the library.

**Comment by serge-sans-paille** [comment]
@gendx thanks for the report, #25 should fix it.
