### ISSUE TITLE
How is Gaussian sampling in NFLlib parameterized?

### ISSUE THREAD

**Issue by iF2007** [quarkslab/NFLlib#27]
I'm looking into this library and would like to bound l2-norm of a vector sampled from discrete Gaussian distribution. A sampled vector example (n=1024, \sigma=3) is [here](https://pastebin.com/8LMq6TT4). Is the distribution parameterized as e^(-x^2/(2\sigma^2)) or e^(-\pi*x^2/s^2)? 

I'm trying to verify the bound of l2-norm of above vector using lemma 2.5 in [this paper](https://arxiv.org/pdf/1506.07490.pdf), where the norm of my example vector is 96.13, which is larger than r=1 case (sqrt(3^2*1024)) for lemma 2.5 in above paper. Since the probability of norm > sqrt(3^2*1024) should extremely small, I would like to know how the discrete Gaussian distribution in NFLlib is parameterized.

Thanks

**Comment by carlosaguilarmelchor** [comment]
Hi,
everything is in the source code :) 

https://github.com/quarkslab/NFLlib/blob/92f8de0d6213bb14c79cc36a842cb3ae5ca8508c/include/nfl/prng/FastGaussianNoise.hpp#L80-L110

Best,
Carlos

**Comment by iF2007** [comment]
@carlosaguilarmelchor Hi Carlos. Thanks for your reply. I notice this header file after I open this issue and everything is clear. Thank you :)
