### ISSUE TITLE
Any future plan to support divide-and-rounding operation for the RNS/CRT format ?

### ISSUE THREAD

**Issue by fionser** [quarkslab/NFLlib#33]
* [Implementation and Performance Evaluation of
RNS Variants of the BFV Homomorphic Encryption
Scheme](https://eprint.iacr.org/2018/589.pdf)

**Comment by carlosaguilarmelchor** [comment]
Hi @fionser,
I am sorry we are not planning to support such operation,
but Pull Requests are welcome !
best,
Carlos
