### ISSUE TITLE
make error under macOS

### ISSUE THREAD

**Issue by ifeelok92** [quarkslab/NFLlib#44]
after I enter the command make，the following prompts：

clang: error: unsupported argument '-q' to option 'Wa,'
make[2]: *** [CMakeFiles/nfllib_static.dir/lib/params/params.cpp.o] Error 1
make[1]: *** [CMakeFiles/nfllib_static.dir/all] Error 2
make: *** [all] Error 2

How can I fix it？

**Comment by ifeelok92** [comment]
verbosed make shows as follows

tianyuandeMacBook-Air:_build xietiany$ make VERBOSE=1
/usr/local/Cellar/cmake/3.12.4/bin/cmake -H/Users/xietiany/NFLlib-master -B/Users/xietiany/NFLlib-master/_build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.12.4/bin/cmake -E cmake_progress_start /Users/xietiany/NFLlib-master/_build/CMakeFiles /Users/xietiany/NFLlib-master/_build/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/nfllib_static.dir/build.make CMakeFiles/nfllib_static.dir/depend
cd /Users/xietiany/NFLlib-master/_build && /usr/local/Cellar/cmake/3.12.4/bin/cmake -E cmake_depends "Unix Makefiles" /Users/xietiany/NFLlib-master /Users/xietiany/NFLlib-master /Users/xietiany/NFLlib-master/_build /Users/xietiany/NFLlib-master/_build /Users/xietiany/NFLlib-master/_build/CMakeFiles/nfllib_static.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/nfllib_static.dir/build.make CMakeFiles/nfllib_static.dir/build
[ 11%] Building CXX object CMakeFiles/nfllib_static.dir/lib/params/params.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DNFL_OPTIMIZED -DNTT_AVX2 -I/Users/xietiany/NFLlib-master/include -I/Users/xietiany/NFLlib-master/include/nfl -I/Users/xietiany/NFLlib-master/include/nfl/arch -I/Users/xietiany/NFLlib-master/include/nfl/opt -I/Users/xietiany/NFLlib-master/include/nfl/opt/arch -I/Users/xietiany/NFLlib-master/include/nfl/prng  -march=native -std=c++11 -DNDEBUG -O3 -march=native -mtune=native -funroll-loops -Wa,-q   -o CMakeFiles/nfllib_static.dir/lib/params/params.cpp.o -c /Users/xietiany/NFLlib-master/lib/params/params.cpp
clang: error: unsupported argument '-q' to option 'Wa,'
make[2]: *** [CMakeFiles/nfllib_static.dir/lib/params/params.cpp.o] Error 1
make[1]: *** [CMakeFiles/nfllib_static.dir/all] Error 2
make: *** [all] Error 2

**Comment by Kirija** [comment]
I think you are supposed to use gcc as the compiler, clang is used for linking AVX assembly and -Wa,-q is the option to tell gcc to link using clang.

**Comment by ifeelok92** [comment]
where should i change my compiler from 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  to g++,  i DON'T know how to change compiler    parameter in your makefile, it is different from usual one as u use cmake.

**Comment by Kirija** [comment]
if you installed gcc (in this example its gcc 4.9) from macport then you can select it by
> sudo port select --set gcc mp-gcc49

And you need to take care of some environment variables such as described in https://stackoverflow.com/questions/27807046/set-cc-to-gcc-instead-of-clang-on-osx-yosemite

**Comment by ifeelok92** [comment]
i fix this issue by modifying the 31st line of CMakeCompilers.txt as
 if(APPLE)
   set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
endif()

**Comment by carlosaguilarmelchor** [comment]
Cool marking it as solved then :)
