### ISSUE TITLE
make test in linux, some errors occurred

### ISSUE THREAD

**Issue by ifeelok92** [quarkslab/NFLlib#46]
98% tests passed, 3 tests failed out of 122

Total Test time (real) =  39.94 sec

The following tests FAILED:
	 98 - run_nfllib_demo1048576_124_uint64_t_op (SEGFAULT)
	114 - run_poly_p1048576_124_uint64_t (SEGFAULT)
	118 - run_poly_mpz1048576_124_uint64_t (SEGFAULT)
Errors while running CTest
Makefile:127: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by gongchengdashao** [comment]
I also have the same error, have you solved it?

**Comment by carlosaguilarmelchor** [comment]
It is not a correctness issue, it just means the stack in your computer is too small to hold the huge variables in this test. If you have a similar issue in your programs (which should not happen if you do not need polynomials of degree 1 million) just allocate the variables in the heap.

**Comment by gongchengdashao** [comment]
thanks ！

**Comment by carlosaguilarmelchor** [comment]
Welcome :)
